version: "3.8"
services:
  client:
    build: .
    ports:
      - 8080:80
    container_name: client
    # environment:
    #   - VUE_APP_API_URL=http://aaa.jiji:9000
    logging:
      options:
          tag: "client"